//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortFolio.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Followers
    {
        public int ID { get; set; }
        public int ID_ProfiloFollowato { get; set; }
        public string ID_Utente { get; set; }
        public string Nome { get; set; }
        public bool IsAncoraFollower { get; set; }
    
        public virtual UtenteIg UtenteIg { get; set; }
    }
}
