//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortFolio.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtenteIg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UtenteIg()
        {
            this.Followers1 = new HashSet<Followers>();
        }
    
        public string ID { get; set; }
        public string Nome { get; set; }
        public string Username { get; set; }
        public int Followers { get; set; }
        public int Seguiti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Followers> Followers1 { get; set; }
    }
}
